application/controllers/chat.py
from flask import session, render_template, request, redirect, Blueprint, url_for

message = Blueprint('message', __name__, static_folder='static')


@message.route('/chat', methods=['GET'])
def root():
    if request.method == 'GET':
        if 'user' in session:
            return render_template('chat.html')
        else:
            return redirect(url_for('register.root'))

application/controllers/forgot.py
from flask import session, render_template, request, redirect, Blueprint

forgotpassword = Blueprint('forgotpassword', __name__, static_folder='static')


@forgotpassword.route('/passwordreset', methods=['GET', 'POST'])
def root():
    if request.method == 'GET':
        return render_template('forgotpassword.html')

application/controllers/googleauth.py
# built-in Python Modules
import json
import os

# external Python Modules
from flask import session, render_template, request, redirect, Blueprint
from oauthlib.oauth2 import WebApplicationClient
import requests
from dotenv import load_dotenv
load_dotenv()
# Blueprint
google = Blueprint('google', __name__, static_folder='static')

# OAuth 2 client setup
auth = WebApplicationClient(os.getenv('GOOGLE_CLIENT_ID'))

GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration"
)


def get_google_provider_cfg():
    return requests.get(GOOGLE_DISCOVERY_URL).json()


@google.route("/google")
def google_auth():
    # find out what URL to hit for Google login
    google_provider_cfg = get_google_provider_cfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    # scopes that let you retrieve user's profile from Google
    request_uri = auth.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@google.route("/google/callback")
def callback():
    # Get authorization code Google sent back
    code = request.args.get("code")
    # Find out what URL to hit to get tokens that allow you to ask for things on behalf of a user
    google_provider_cfg = get_google_provider_cfg()
    token_endpoint = google_provider_cfg["token_endpoint"]
    # Prepare and send a request to get tokens
    token_url, headers, body = auth.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(os.getenv('GOOGLE_CLIENT_ID'),
              os.getenv('GOOGLE_CLIENT_SECRET')),
    )

    # Parse the fucking tokens!
    auth.parse_request_body_response(json.dumps(token_response.json()))
    # user's profile information, including their Google profile image and email
    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = auth.add_token(userinfo_endpoint)
    # lets grab that user infos
    userinfo_response = requests.get(uri, headers=headers, data=body)
    # quick sanity check before accessing data
    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]

        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
        return users_email
    else:
        return "User email not available or not verified by Google.", 400

application/controllers/register.py
# external Python Modules
from flask import session, render_template, request, redirect, Blueprint, url_for

# local Python Modules
from application.models.user import User
import application

signup = Blueprint('register', __name__)


@signup.route('/register', methods=['GET', 'POST'])
def root():
    if request.method == 'GET':
        if 'user' in session:
            return redirect(url_for('index.root'))
        else:
            return render_template('register.html')
    if request.method == 'POST':
        credentials = request.form
        email = credentials.get('email')
        pw = credentials.get('password')
        # if we find a user in the database return that user exists and redirect the client to the register form with an error message
        if application.user.find_one({"email": email}):
            # change to login later
            return redirect(url_for('register.root'))
        else:
            new_user = User(email=email, password=pw)
            # generate UUID
            new_user.set_uuid()
            new_user.save_new()
            session['user'] = email
            return redirect(url_for('q.root'))

application/templates/405.html
<!doctype html>
<html lang="en">


<!-- Mirrored from pipeline.mediumra.re/utility-error.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Feb 2020 07:31:18 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-52115242-14"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-52115242-14');
    </script>
    <meta charset="utf-8">
    <title>Pipeline Project Management Bootstrap Theme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A project management Bootstrap theme by Medium Rare">
    <link href="static/img/favicon.ico" rel="icon" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
    <link href="static/css/theme.css" rel="stylesheet" type="text/css" media="all" />
</head>

<body>
    <div class="main-container fullscreen">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5 col-lg-6 col-md-7">
                    <div class="text-center">
                        <h1 class="display-1 text-primary">4&#x1f635;5</h1>
                        <p>
                            The page you were looking for was not found. <a href="index.html">Click here to go home</a>
                            or <a href="#">Contact Us</a> if you think this might be an error.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Required vendor scripts (Do not remove) -->
    <script type="text/javascript" src="static/js/jquery.min.js"></script>
    <script type="text/javascript" src="static/js/popper.min.js"></script>
    <script type="text/javascript" src="static/js/bootstrap.js"></script>

    <!-- Optional Vendor Scripts (Remove the plugin script here and comment initializer script out of index.js if site does not use that feature) -->

    <!-- Autosize - resizes textarea inputs as user types -->
    <script type="text/javascript" src="static/js/autosize.min.js"></script>
    <!-- Flatpickr (calendar/date/time picker UI) -->
    <script type="text/javascript" src="static/js/flatpickr.min.js"></script>
    <!-- Prism - displays formatted code boxes -->
    <script type="text/javascript" src="static/js/prism.js"></script>
    <!-- Shopify Draggable - drag, drop and sort items on page -->
    <script type="text/javascript" src="static/js/draggable.bundle.legacy.js"></script>
    <script type="text/javascript" src="static/js/swap-animation.js"></script>
    <!-- Dropzone - drag and drop files onto the page for uploading -->
    <script type="text/javascript" src="static/js/dropzone.min.js"></script>
    <!-- List.js - filter list elements -->
    <script type="text/javascript" src="static/js/list.min.js"></script>

    <!-- Required theme scripts (Do not remove) -->
    <script type="text/javascript" src="static/js/theme.js"></script>

    <!-- This appears in the demo only - demonstrates different layouts -->
    <style type="text/css">
        .layout-switcher {
            position: fixed;
            bottom: 0;
            left: 50%;
            transform: translateX(-50%) translateY(73px);
            color: #fff;
            transition: all .35s ease;
            background: #343a40;
            border-radius: .25rem .25rem 0 0;
            padding: .75rem;
            z-index: 999;
        }

        .layout-switcher:not(:hover) {
            opacity: .95;
        }

        .layout-switcher:not(:focus) {
            cursor: pointer;
        }

        .layout-switcher-head {
            font-size: .75rem;
            font-weight: 600;
            text-transform: uppercase;
        }

        .layout-switcher-head i {
            font-size: 1.25rem;
            transition: all .35s ease;
        }

        .layout-switcher-body {
            transition: all .55s ease;
            opacity: 0;
            padding-top: .75rem;
            transform: translateY(24px);
            text-align: center;
        }

        .layout-switcher:focus {
            opacity: 1;
            outline: none;
            transform: translateX(-50%) translateY(0);
        }

        .layout-switcher:focus .layout-switcher-head i {
            transform: rotateZ(180deg);
            opacity: 0;
        }

        .layout-switcher:focus .layout-switcher-body {
            opacity: 1;
            transform: translateY(0);
        }

        .layout-switcher-option {
            width: 72px;
            padding: .25rem;
            border: 2px solid rgba(255, 255, 255, 0);
            display: inline-block;
            border-radius: 4px;
            transition: all .35s ease;
        }

        .layout-switcher-option.active {
            border-color: #007bff;
        }

        .layout-switcher-icon {
            width: 100%;
            border-radius: 4px;
        }

        .layout-switcher-body:hover .layout-switcher-option:not(:hover) {
            opacity: .5;
            transform: scale(0.9);
        }

        @media all and (max-width: 990px) {
            .layout-switcher {
                min-width: 250px;
            }
        }

        @media all and (max-width: 767px) {
            .layout-switcher {
                display: none;
            }
        }
    </style>
    <div class="layout-switcher" tabindex="1">
        <div class="layout-switcher-head d-flex justify-content-between">
            <span>Select Layout</span>
            <i class="material-icons">arrow_drop_up</i>
        </div>
        <div class="layout-switcher-body">

        </div>
    </div>

</body>


<!-- Mirrored from pipeline.mediumra.re/utility-error.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Feb 2020 07:31:18 GMT -->

</html>

application/templates/forgotpassword.html
<!doctype html>
<html lang="en">


<!-- Mirrored from pipeline.mediumra.re/utility-forgot-password.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Feb 2020 07:31:18 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->

<head>

  <meta charset="utf-8">
  <title>Pipeline Project Management Bootstrap Theme</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A project management Bootstrap theme by Medium Rare">
  <link href="static/img/favicon.ico" rel="icon" type="image/x-icon">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
  <link href="static/css/theme.css" rel="stylesheet" type="text/css" media="all" />
</head>

<body>
  <div class="main-container fullscreen">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-7">
          <div class="text-center">
            <h1 class="h2">Forgot password &#x1f62B;</h1>
            <p class="lead">Enter your email address to reset</p>
            <form>
              <div class="form-group">
                <input class="form-control" type="email" placeholder="Email Address" name="forgot-password-email" />
              </div>
              <button class="btn btn-lg btn-block btn-primary" role="button" type="submit">
                Send reset link
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Required vendor scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/jquery.min.js"></script>
  <script type="text/javascript" src="static/js/popper.min.js"></script>
  <script type="text/javascript" src="static/js/bootstrap.js"></script>

  <!-- Optional Vendor Scripts (Remove the plugin script here and comment initializer script out of index.js if site does not use that feature) -->

  <!-- Autosize - resizes textarea inputs as user types -->
  <script type="text/javascript" src="static/js/autosize.min.js"></script>
  <!-- Flatpickr (calendar/date/time picker UI) -->
  <script type="text/javascript" src="static/js/flatpickr.min.js"></script>
  <!-- Prism - displays formatted code boxes -->
  <script type="text/javascript" src="static/js/prism.js"></script>
  <!-- Shopify Draggable - drag, drop and sort items on page -->
  <script type="text/javascript" src="static/js/draggable.bundle.legacy.js"></script>
  <script type="text/javascript" src="static/js/swap-animation.js"></script>
  <!-- Dropzone - drag and drop files onto the page for uploading -->
  <script type="text/javascript" src="static/js/dropzone.min.js"></script>
  <!-- List.js - filter list elements -->
  <script type="text/javascript" src="static/js/list.min.js"></script>

  <!-- Required theme scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/theme.js"></script>

  <!-- This appears in the demo only - demonstrates different layouts -->
  <style type="text/css">
    .layout-switcher {
      position: fixed;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%) translateY(73px);
      color: #fff;
      transition: all .35s ease;
      background: #343a40;
      border-radius: .25rem .25rem 0 0;
      padding: .75rem;
      z-index: 999;
    }

    .layout-switcher:not(:hover) {
      opacity: .95;
    }

    .layout-switcher:not(:focus) {
      cursor: pointer;
    }

    .layout-switcher-head {
      font-size: .75rem;
      font-weight: 600;
      text-transform: uppercase;
    }

    .layout-switcher-head i {
      font-size: 1.25rem;
      transition: all .35s ease;
    }

    .layout-switcher-body {
      transition: all .55s ease;
      opacity: 0;
      padding-top: .75rem;
      transform: translateY(24px);
      text-align: center;
    }

    .layout-switcher:focus {
      opacity: 1;
      outline: none;
      transform: translateX(-50%) translateY(0);
    }

    .layout-switcher:focus .layout-switcher-head i {
      transform: rotateZ(180deg);
      opacity: 0;
    }

    .layout-switcher:focus .layout-switcher-body {
      opacity: 1;
      transform: translateY(0);
    }

    .layout-switcher-option {
      width: 72px;
      padding: .25rem;
      border: 2px solid rgba(255, 255, 255, 0);
      display: inline-block;
      border-radius: 4px;
      transition: all .35s ease;
    }

    .layout-switcher-option.active {
      border-color: #007bff;
    }

    .layout-switcher-icon {
      width: 100%;
      border-radius: 4px;
    }

    .layout-switcher-body:hover .layout-switcher-option:not(:hover) {
      opacity: .5;
      transform: scale(0.9);
    }

    @media all and (max-width: 990px) {
      .layout-switcher {
        min-width: 250px;
      }
    }

    @media all and (max-width: 767px) {
      .layout-switcher {
        display: none;
      }
    }
  </style>
  <div class="layout-switcher" tabindex="1">
    <div class="layout-switcher-head d-flex justify-content-between">
      <span>Select Layout</span>
      <i class="material-icons">arrow_drop_up</i>
    </div>
    <div class="layout-switcher-body">

    </div>
  </div>

</body>



</html>

application/templates/login.html
<!doctype html>
<html lang="en">


<!-- Mirrored from pipeline.mediumra.re/utility-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Feb 2020 07:31:18 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->

<head>

  <meta charset="utf-8">
  <title>Pipeline Project Management Bootstrap Theme</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A project management Bootstrap theme by Medium Rare">
  <link href="static/img/favicon.ico" rel="icon" type="image/x-icon">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
  <link href="static/css/theme.css" rel="stylesheet" type="text/css" media="all" />
</head>

<body>
  <div class="main-container fullscreen">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-7">
          <div class="text-center">
            <h1 class="h2">Welcome Back &#x1f44b;</h1>
            <p class="lead">Log in to your account to continue</p>
            <form method="POST">
              <div class="form-group">
                <input class="form-control" type="email" placeholder="Email Address" name="email" />
              </div>
              <div class="form-group">
                <input class="form-control" type="password" placeholder="Password" name="password" />
                <div class="text-right">
                  <small><a href="{{url_for('forgotpassword.root')}}">Forgot password?</a>
                  </small>
                </div>
              </div>
              <button class="btn btn-lg btn-block btn-primary" role="button" type="submit">
                Log in
              </button>
              <small>Don't have an account yet? <a href="{{url_for('register.root')}}">Create one</a>
              </small>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Required vendor scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/jquery.min.js"></script>
  <script type="text/javascript" src="static/js/popper.min.js"></script>
  <script type="text/javascript" src="static/js/bootstrap.js"></script>

  <!-- Optional Vendor Scripts (Remove the plugin script here and comment initializer script out of index.js if site does not use that feature) -->

  <!-- Autosize - resizes textarea inputs as user types -->
  <script type="text/javascript" src="static/js/autosize.min.js"></script>
  <!-- Flatpickr (calendar/date/time picker UI) -->
  <script type="text/javascript" src="static/js/flatpickr.min.js"></script>
  <!-- Prism - displays formatted code boxes -->
  <script type="text/javascript" src="static/js/prism.js"></script>
  <!-- Shopify Draggable - drag, drop and sort items on page -->
  <script type="text/javascript" src="static/js/draggable.bundle.legacy.js"></script>
  <script type="text/javascript" src="static/js/swap-animation.js"></script>
  <!-- Dropzone - drag and drop files onto the page for uploading -->
  <script type="text/javascript" src="static/js/dropzone.min.js"></script>
  <!-- List.js - filter list elements -->
  <script type="text/javascript" src="static/js/list.min.js"></script>

  <!-- Required theme scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/theme.js"></script>

  <!-- This appears in the demo only - demonstrates different layouts -->
  <style type="text/css">
    .layout-switcher {
      position: fixed;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%) translateY(73px);
      color: #fff;
      transition: all .35s ease;
      background: #343a40;
      border-radius: .25rem .25rem 0 0;
      padding: .75rem;
      z-index: 999;
    }

    .layout-switcher:not(:hover) {
      opacity: .95;
    }

    .layout-switcher:not(:focus) {
      cursor: pointer;
    }

    .layout-switcher-head {
      font-size: .75rem;
      font-weight: 600;
      text-transform: uppercase;
    }

    .layout-switcher-head i {
      font-size: 1.25rem;
      transition: all .35s ease;
    }

    .layout-switcher-body {
      transition: all .55s ease;
      opacity: 0;
      padding-top: .75rem;
      transform: translateY(24px);
      text-align: center;
    }

    .layout-switcher:focus {
      opacity: 1;
      outline: none;
      transform: translateX(-50%) translateY(0);
    }

    .layout-switcher:focus .layout-switcher-head i {
      transform: rotateZ(180deg);
      opacity: 0;
    }

    .layout-switcher:focus .layout-switcher-body {
      opacity: 1;
      transform: translateY(0);
    }

    .layout-switcher-option {
      width: 72px;
      padding: .25rem;
      border: 2px solid rgba(255, 255, 255, 0);
      display: inline-block;
      border-radius: 4px;
      transition: all .35s ease;
    }

    .layout-switcher-option.active {
      border-color: #007bff;
    }

    .layout-switcher-icon {
      width: 100%;
      border-radius: 4px;
    }

    .layout-switcher-body:hover .layout-switcher-option:not(:hover) {
      opacity: .5;
      transform: scale(0.9);
    }

    @media all and (max-width: 990px) {
      .layout-switcher {
        min-width: 250px;
      }
    }

    @media all and (max-width: 767px) {
      .layout-switcher {
        display: none;
      }
    }
  </style>
  <div class="layout-switcher" tabindex="1">
    <div class="layout-switcher-head d-flex justify-content-between">
      <span>Select Layout</span>
      <i class="material-icons">arrow_drop_up</i>
    </div>
    <div class="layout-switcher-body">

    </div>
  </div>

</body>


<!-- Mirrored from pipeline.mediumra.re/utility-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Feb 2020 07:31:18 GMT -->

</html>

application/templates/register.html
<!doctype html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <title>Pipeline Project Management Bootstrap Theme</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A project management Bootstrap theme by Medium Rare">
  <link href="static/img/favicon.ico" rel="icon" type="image/x-icon">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
  <link href="static/css/theme.css" rel="stylesheet" type="text/css" media="all" />
</head>

<body>
  <div class="main-container fullscreen">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-7">
          <div class="text-center">
            <h1 class="h2">Create account</h1>
            <p class="lead">Start doing things for free, in an instant</p>
            <a href="{{url_for('google.google_auth')}}"><button class="btn btn-lg btn-block btn-primary">
                <img alt="Google" src="static/img/logo-google.svg" class="rounded align-top mr-2" />Continue with Google
              </button></a>

            <hr>
            <form method="POST">
              <div class="form-group">
                <input class="form-control" type="email" placeholder="Email Address" name="email" />
              </div>
              <div class="form-group">
                <input class="form-control" type="password" placeholder="Password" name="password" />
                <div class="text-left">
                  <small>Your password should be at least 8 characters</small>
                </div>
              </div>
              <button class="btn btn-lg btn-block btn-primary" role="button" type="submit">
                Create account
              </button>
              <small>By clicking 'Create Account' you agree to our <a href="#">Terms of Use</a>
              </small>
              <br>
              <small>Already have an account? Then <a href="{{url_for('login.root')}}">Login</a>
              </small>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Required vendor scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/jquery.min.js"></script>
  <script type="text/javascript" src="static/js/popper.min.js"></script>
  <script type="text/javascript" src="static/js/bootstrap.js"></script>

  <!-- Optional Vendor Scripts (Remove the plugin script here and comment initializer script out of index.js if site does not use that feature) -->

  <!-- Autosize - resizes textarea inputs as user types -->
  <script type="text/javascript" src="static/js/autosize.min.js"></script>
  <!-- Flatpickr (calendar/date/time picker UI) -->
  <script type="text/javascript" src="static/js/flatpickr.min.js"></script>
  <!-- Prism - displays formatted code boxes -->
  <script type="text/javascript" src="static/js/prism.js"></script>
  <!-- Shopify Draggable - drag, drop and sort items on page -->
  <script type="text/javascript" src="static/js/draggable.bundle.legacy.js"></script>
  <script type="text/javascript" src="static/js/swap-animation.js"></script>
  <!-- Dropzone - drag and drop files onto the page for uploading -->
  <script type="text/javascript" src="static/js/dropzone.min.js"></script>
  <!-- List.js - filter list elements -->
  <script type="text/javascript" src="static/js/list.min.js"></script>

  <!-- Required theme scripts (Do not remove) -->
  <script type="text/javascript" src="static/js/theme.js"></script>

  <!-- This appears in the demo only - demonstrates different layouts -->
  <style type="text/css">
    .layout-switcher {
      position: fixed;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%) translateY(73px);
      color: #fff;
      transition: all .35s ease;
      background: #343a40;
      border-radius: .25rem .25rem 0 0;
      padding: .75rem;
      z-index: 999;
    }

    .layout-switcher:not(:hover) {
      opacity: .95;
    }

    .layout-switcher:not(:focus) {
      cursor: pointer;
    }

    .layout-switcher-head {
      font-size: .75rem;
      font-weight: 600;
      text-transform: uppercase;
    }

    .layout-switcher-head i {
      font-size: 1.25rem;
      transition: all .35s ease;
    }

    .layout-switcher-body {
      transition: all .55s ease;
      opacity: 0;
      padding-top: .75rem;
      transform: translateY(24px);
      text-align: center;
    }

    .layout-switcher:focus {
      opacity: 1;
      outline: none;
      transform: translateX(-50%) translateY(0);
    }

    .layout-switcher:focus .layout-switcher-head i {
      transform: rotateZ(180deg);
      opacity: 0;
    }

    .layout-switcher:focus .layout-switcher-body {
      opacity: 1;
      transform: translateY(0);
    }

    .layout-switcher-option {
      width: 72px;
      padding: .25rem;
      border: 2px solid rgba(255, 255, 255, 0);
      display: inline-block;
      border-radius: 4px;
      transition: all .35s ease;
    }

    .layout-switcher-option.active {
      border-color: #007bff;
    }

    .layout-switcher-icon {
      width: 100%;
      border-radius: 4px;
    }

    .layout-switcher-body:hover .layout-switcher-option:not(:hover) {
      opacity: .5;
      transform: scale(0.9);
    }

    @media all and (max-width: 990px) {
      .layout-switcher {
        min-width: 250px;
      }
    }

    @media all and (max-width: 767px) {
      .layout-switcher {
        display: none;
      }
    }
  </style>
  <div class="layout-switcher" tabindex="1">
    <div class="layout-switcher-head d-flex justify-content-between">
      <span>Select Layout</span>
      <i class="material-icons">arrow_drop_up</i>
    </div>
    <div class="layout-switcher-body">

    </div>
  </div>

</body>



</html>